language: node_js
services:
  - redis-server
env:
  - TEST_CMD="test"
  - TEST_CMD="lint"
node_js:
  - 8
script:
  - npm run $TEST_CMD
before_script:
  - npm install -g grunt-cli
after_script:
  - if [ "$TEST_CMD" = 'test' ]; then npm run coveralls; fi
sudo: false