language: node_js
services:
  - redis-server
env:
  - TEST_CMD="test"
  - TEST_CMD="mocha"
node_js:
  - "0.10"
script:
  - npm run $TEST_CMD
before_script:
  - npm install -g grunt-cli
after_script:
  - npm run coveralls